Repository tenstorrent/tt-forge, pull requests merged in 2025-06, with the labels that each got.

#154 Fix for new wheels and add revoke pypi version
  .github/actions/build-release/action.yml
  .github/actions/docs-generator/action.yml
  .github/actions/set-release-facts/action.yaml
  .github/workflows/daily-releaser.yml
  .github/workflows/remove-tenstorrent-pypi.yml
Labels: CI/Infra

#160 Removing remove from pypi action
  .github/workflows/remove-tenstorrent-pypi.yml
Labels: CI/Infra

#179 Use install-artifacts-release from tt-torch
  .github/actions/set-release-facts/action.yaml
Labels: CI/Infra

#184 Fix wheel name in release facts
  .github/actions/set-release-facts/action.yaml
Labels: bug, CI/Infra

#185 add skip wheel install fact
  .github/actions/publish-tenstorrent-pypi/action.yml
  .github/actions/set-release-facts/action.yaml
  .github/actions/tt-forge-wheel/action.yml
Labels: bug, CI/Infra

#215 Add test cleanup workflow for release testing
  .github/actions/wait-workflow/action.yml
  .github/workflows/clean-release-tests.yml
Labels: bug
